name: run-market-bot
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET_KEY: ${{ secrets.X_API_SECRET_KEY }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          FRED_KEY: ${{ secrets.FRED_KEY }}
          TARGET_SYMBOLS: ${{ secrets.TARGET_SYMBOLS }}
        run: |
          python bot.py

      - name: Commit state if changed
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions[bot]"
          if [[ `git status --porcelain` ]]; then
            git add last_state.json || true
            git commit -m "update last_state.json [ci skip]" || true
            git push || true
          else
            echo "no changes"
          fi
